name: AutoRewarder Diario Multicuenta con Edge

on:
  schedule:
    # Se ejecuta todos los días a las 06:00 AM UTC
    - cron: '0 10 * * *'
  workflow_dispatch: # Botón para activarlo manualmente

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v4

    - name: Conectar a tu VPN Doméstica (Tailscale)
      uses: tailscale/github-action@v2
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
        # Añadimos --accept-routes para enlazar correctamente el tráfico con tu PC
        args: --exit-node=pc-grande --accept-routes=true


    - name: Instalar Microsoft Edge en la máquina virtual
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common apt-transport-https wget
        wget -q https://microsoft.com -O- | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://microsoft.com stable main"
        sudo apt-get update
        sudo apt-get install -y microsoft-edge-stable

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-cache-dependency-path: '**/requirements.txt'
        python-version: '3.10'

    - name: Instalar dependencias del Bot
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Crear archivo de cuentas seguro
      env:
        CUENTAS_SECRET: ${{ secrets.CUENTAS_JSON }}
      run: |
        # Esto genera el archivo accounts.json de forma temporal en la máquina virtual
        echo "$CUENTAS_SECRET" > accounts.json

    - name: Ejecutar AutoRewarder en cadena
      run: |
        # Ejecuta el bot pasándole Edge como navegador predeterminado
        # El script leerá automáticamente el archivo accounts.json que acabamos de crear
        python AutoRewarder_CLI.py --headless --browser edge
